# Generated by Django 5.1.5 on 2025-02-17 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('changamoto', models.CharField(blank=True, max_length=100, null=True)),
                ('Biblia', models.CharField(blank=True, max_length=100, null=True)),
                ('kesha', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('lesson', models.CharField(blank=True, max_length=100, null=True)),
                ('deacon', models.CharField(blank=True, max_length=100, null=True)),
                ('nyimbo', models.CharField(blank=True, max_length=100, null=True)),
                ('maombi', models.CharField(blank=True, max_length=100, null=True)),
                ('maombitime', models.CharField(blank=True, max_length=100, null=True)),
                ('ibada', models.CharField(blank=True, max_length=100, null=True)),
                ('jtano', models.CharField(blank=True, max_length=100, null=True)),
                ('ijumaa', models.CharField(blank=True, max_length=100, null=True)),
                ('sabato', models.CharField(blank=True, max_length=100, null=True)),
                ('zaka', models.CharField(blank=True, max_length=100, null=True)),
                ('sadaka', models.CharField(blank=True, max_length=100, null=True)),
                ('makambi', models.CharField(blank=True, max_length=100, null=True)),
                ('michango', models.CharField(blank=True, max_length=100, null=True)),
                ('misaada', models.CharField(blank=True, max_length=100, null=True)),
                ('thamani', models.CharField(blank=True, max_length=100, null=True)),
                ('injili', models.CharField(blank=True, max_length=100, null=True)),
                ('mudawakuhubiri', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Setie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=100)),
                ('value', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='Setting',
        ),
    ]
