# Generated by Django 5.1.5 on 2025-02-17 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authapp', '0002_member_setie_delete_setting'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeaconInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('jumla', models.CharField(max_length=50)),
            ],
        ),
    ]
